### ISSUE TITLE
리뷰 부탁드립니다! 

### ISSUE THREAD

**Issue by hanbitk** [hanbitk/todo-level2#1]
안녕하세요 매니저님! 
작성한 코드 리뷰 부탁드립니다.  개선할 점도 알려주시면 감사하겠습니다. 

감사합니다!

**Comment by piggggggggy** [comment]
안녕하세요! 한빛님!
일단 고생하셨습니다!
lv2의 핵심 포인트인 Redux의 활용측면에서는 더할나위 없이 잘 구현하신 것 같아요.
각각의 action creator와 reducer, 그리고 dispatch하는 함수의 역할도 명확하고, 코드읽기도 매우 좋았습니다.
`uuid` 함수도 분리해서 만드신 것도 매우 좋은 것 같아요. 다만 함수이름은 `uuid`보다는 `getUUID` 같은 동사형으로 작명하시면 더 좋을 것 같습니다!
Redux를 잘 이해하시고 사용하신 것 같네요.

굳이 개선할만한 부분을 말씀드리자면,
Component의 분리가 조금 아쉬운 것 같아요. 
Styled Component의 이름을 명확하게 지어주셨고 `St`라는 prefix를 활용하셔서 확실하게 구분가게 만들어주셔서 전체적으로 코드를 읽는데 불편함은 없었는데, 컴포넌트의 분리는 딱 기능을 기준으로만 나눠 주셨더라구요! 반복되는 부분들이 명확하게 있어서 이 부분을 컴포넌트화해주셨으면 더 좋은 코드였을 것 같습니다!

하지만 지금도 절대 나쁘지는 않습니다!

**Comment by hanbitk** [comment]
매니저님 안녕하세요! 
리뷰 감사드립니다~ 말씀하신점 잘 이해했습니다! 코드 수정 해보도록 할게요 :)

**Comment by hanbitk** [comment]
안녕하세요, 매니저님! 

코드 수정한거 한번더 리뷰해주실 수 있나요? 아직도 개선할 점이 있다면 어떤 부분일까요?
